---
name: sgit

options:
  bundleIdPrefix: net.nedron
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "26.5"
  generateEmptyDirectories: false

settings:
  base:
    SWIFT_VERSION: 5.9
    MARKETING_VERSION: "1.0.6"

packages:
  GitKit:
    url: https://github.com/dnedrow/GitKit.git
    exactVersion: 1.0.6

targets:
  sgit:
    type: tool
    platform: macOS
    sources:
      - path: Sources
    dependencies:
      - package: GitKit
    settings:
      base:
        PRODUCT_NAME: sgit
        PRODUCT_BUNDLE_IDENTIFIER: net.nedron.sgit
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: RELEASE
        SWIFT_OBJC_BRIDGING_HEADER: Sources/Bridging/sgit-Bridging-Header.h
        OTHER_LDFLAGS: -lz
        GENERATE_INFOPLIST_FILE: true
        CREATE_INFOPLIST_SECTION_IN_BINARY: true

schemes:
  sgit:
    build:
      targets:
        sgit: all
    run:
      config: Debug
